export default [
    {
        id: 1,
        name: "Michael Scott",
        title: "Regional Manager",
        description: "Michael is the heart and soul of our Scranton branch. With his unparalleled enthusiasm and unique leadership style, he keeps the office buzzing with energy. Despite his occasional eccentricities, Michael's dedication to the team and his passion for paper are undeniable.",
        coverImg: "alt.png",
    },
    {
        id: 2,
        name: "Dwight Schrute",
        title: "Assistant to the Regional Manager",
        description: "Meet Dwight, our resident \"Assistant to the Regional Manager\" and beet aficionado. With his unwavering commitment to Dunder Mifflin and his no-nonsense approach to work, Dwight ensures that our office operates at maximum efficiency. Just don't get on his bad side!",
        coverImg: "alt.png",
    },
    {
        id: 3,
        name: "Jim Halpert",
        title: "Sales Representative",
        description: "Jim brings a refreshing dose of humor and charm to the sales team. Known for his quick wit and playful antics, he keeps spirits high even during the most challenging days. But don't let his laid-back demeanor fool you—Jim is a sales powerhouse with a knack for sealing the deal.",
        coverImg: "alt.png",
    },
    {
        id: 4,
        name: "Pam Beesly",
        title: "Receptionist",
        description: "Pam is the friendly face that greets you as you enter our office. Beyond her duties at the front desk, she's also a talented artist with big dreams. Pam's kindness and creativity make her an invaluable member of our team, and her budding romance with Jim adds a touch of sweetness to the workplace.",
        coverImg: "alt.png",
    },
    {
        id: 5,
        name: "Stanley Hudson",
        title: "Sales Representative",
        description: "With his dry humor and love of crossword puzzles, Stanley brings a sense of calm to the sales department. He's a no-nonsense salesman who gets the job done efficiently and effectively. When Stanley speaks, you know it's time to listen.",
        coverImg: "alt.png",
    },
    {
        id: 6,
        name: "Phyllis Vance",
        title: "Sales Representative",
        description: "Phyllis is the warm and nurturing presence in our sales team. Her gentle demeanor and motherly advice make her a beloved figure in the office. But don't let her sweetness fool you—Phyllis is a savvy saleswoman who knows how to close a deal.",
        coverImg: "alt.png",
    },
    {
        id: 7,
        name: "Kevin Malone",
        title: "Accountant",
        description: "Kevin's cheerful personality and love of snacks brighten up the accounting department. While he may not always be the most focused employee, his heart of gold and unwavering loyalty to his colleagues make him an essential part of the team.",
        coverImg: "alt.png",
    },
    {
        id: 8,
        name: "Angela Martin",
        title: "Senior Accountant",
        description: "Meet Angela, our meticulous senior accountant with a soft spot for felines. While she may come across as stern at times, Angela's attention to detail ensures that our finances are always in order. Just be sure to keep your desk clean—she's not a fan of clutter!",
        coverImg: "alt.png",
    },
    {
        id: 9,
        name: "Oscar Martinez",
        title: "Accountant",
        description: "Oscar is the voice of reason in our accounting department. With his sharp intellect and dry wit, he keeps the team grounded amidst the chaos of office life. Whether it's balancing the books or offering sage advice, Oscar is always there when you need him.",
        coverImg: "alt.png",
    },
    {
        id: 10,
        name: "Creed Bratton",
        title: "Quality Assurance Director",
        description: "Creed may be a bit of an enigma, but his expertise in quality assurance is unmatched. With his unconventional wisdom and mysterious past, he brings an air of intrigue to the office. Just don't ask too many questions about his past—some secrets are better left undiscovered.",
        coverImg: "alt.png",
    }
]